### ISSUE TITLE
Allow to configure MaxAuthTries

### ISSUE THREAD

**Issue by runningman84** [dev-sec/chef-ssh-hardening#100]
We would like to configure MaxAuthTries to a custom value. If you use a ssh-agent with multiple keys, the default value might be too low.

**Comment by chris-rock** [comment]
We are happy to accept PRs that make this value configurable.

**Comment by elijah** [comment]
Should be resolved / can be closed - see commit 66e7ebfd11dc696f5ba56e8e17b10c92f6eeb23b
