### ISSUE TITLE
Failures when running kitchen test with tests-compliance-ssh profile

### ISSUE THREAD

**Issue by vjeffrey** [dev-sec/chef-ssh-hardening#113]
Failures take place on ubuntu 15, centos 66, centos 67, oracle 66, oracle 67, debian 6, and debian 8.

https://chefio.slack.com/files/vj/F0Q0224LB/ubuntu-15_fail.txt
https://chefio.slack.com/files/vj/F0PVD99EG/centos-66_fail.txt
https://chefio.slack.com/files/vj/F0Q086RLZ/oracle-66_fail.txt
https://chefio.slack.com/files/vj/F0Q06V88P/oracle-67_fail.txt
https://chefio.slack.com/files/vj/F0Q02RG84/debian-6_fail.txt
https://chefio.slack.com/files/vj/F0Q0B6801/debian-8_fail.txt

**Comment by jrake-revelant** [comment]
Your files are behind a login :( Can you provide them via e.g. publics gists?

Cheers

**Comment by artem-sidorenko** [comment]
@vjeffrey I'm closing this as there is no response. Feel free to reopen if the problem is still present
