### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/chef-ssh-hardening#133]
As you probably noticed, after some years of inactivity, I finally have time for such things:)

I would like to get the chef part of dev-sec into the "active maintained" state. So I started with ssh-hardening part.

I already created a 2.0.0 milestone and assigned some issues with breaking changes. I will cleanup/resolve all other issues without breaking changes for 1.3.0 release.

This issue is thought to be for discussions/ideas/topics around 2.0.0.

Right now I have only some questions:
 - Who is available for review of PRs? Who is interested in discussions, e.g. about breaking changes? @atomic111 ?:-)
 - Who is releasing to supermarket? @chris-rock ?:-)

**Comment by chris-rock** [comment]
@artem-sidorenko I am happy to do reviews and I am also happy to give you access to push released to supermarket

**Comment by atomic111** [comment]
@artem-sidorenko i will also review and help you with the update

**Comment by artem-sidorenko** [comment]
@chris-rock @arlimus can you maybe add me as collaborator on the supermarket for hardening cookbooks?

**Comment by artem-sidorenko** [comment]
2.0.0 is ready so far, I'm creating the changelog and would tag the master. After this I'll start to write the release notes in the blog and would upload 2.0.0 to supermarket after the blogpost is online
