### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/chef-ssh-hardening#135]
Me and @atomic111 agreed today to include the #132 in the 1.3.0. Everything else will go to the 2.0.0 (#133).

The plan is to wait another week for feedback on #132. If there is no feedback, to merge it as-is and to release 1.3.0.

**Comment by artem-sidorenko** [comment]
@atomic111 it makes sense to have #138 prior to 1.3.0. Currently we do not have any supported distro information on supermarket

**Comment by chris-rock** [comment]
@artem-sidorenko @atomic111 I like that approach

**Comment by artem-sidorenko** [comment]
@atomic111 I see you tagged the 1.3.0, but its not on the supermarket yet. Are there any troubles? Can I help somehow?

**Comment by artem-sidorenko** [comment]
I pushed 1.3.0 to the supermarked and updated the releases page here
