### ISSUE TITLE
Error message about DSA key on RHEL 7

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/chef-ssh-hardening#158]
I see following messages in the logs of RHEL 7 systems with applied ssh-hardening:

```
Jan  4 09:00:07 node sshd[25777]: error: Could not load host key: /etc/ssh/ssh_host_dsa_key
```

@atomic111 @chris-rock can we completely drop the support of DSA host key? (to remove the dsa key option from the `host_key_files` array)

**Comment by artem-sidorenko** [comment]
@atomic111 ping

**Comment by atomic111** [comment]
@artem-sidorenko from the security point of view DSA is secure and more complex to crack it as RSA. So i would still keep this. the problem is, that the DSA Host key is not created. maybe we add a function to create the host keys

**Comment by artem-sidorenko** [comment]
@atomic111 what do you think about [this analyses and explanations](http://security.stackexchange.com/questions/112802/why-openssh-deprecated-dsa-keys/112818#112818)?

**Comment by artem-sidorenko** [comment]
and here another peace: https://www.gentoo.org/support/news-items/2015-08-13-openssh-weak-keys.html

Bettercrypto also do not have DSA keys (see [here, page 23](https://bettercrypto.org/static/applied-crypto-hardening.pdf). 

And [here is the important reference](https://bugzilla.mindrot.org/show_bug.cgi?id=1647) to the openssh upstream on this topic.

As I understand, one of the key points is DSA key length of 1024, and this is still the case, from the man page of ssh-keygen on ubuntu-16.04:

> DSA keys must be exactly 1024 bits as specified by FIPS 186-2.

@atomic111 maybe we should consider the removal of DSA from defaults here?

**Comment by atomic111** [comment]
@artem-sidorenko ok the Problem is not the algorithem, it is the key length. because it is more complex to solve the discrete log problem then facturing. http://digitalassets.lib.berkeley.edu/techreports/ucb/text/CSD-84-186.pdf

Ok, we have no possibility to increase the key size, then we have to remove it. I agree
