### ISSUE TITLE
Verify the current crypto settings

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/chef-ssh-hardening#162]
@bazbremner raised this point in the GH-141 and myself and @atomic111 had this topic also in some phone call in the last days

So we should check following things:
- [kex, macs, ciphers](https://github.com/dev-sec/chef-ssh-hardening/blob/244ff5f13e583c141140926b5188bab2bbb5caaf/libraries/devsec_ssh.rb#L46-L67)
- used algorithms for public key authentication - currently we use RSA and ECDSA, DSA is going to be removed (GH-161)

My idea would be to go completely through the following docs and check the things above:
 - https://stribika.github.io/2015/01/04/secure-secure-shell.html
 - https://bettercrypto.org/static/applied-crypto-hardening.pdf

I already have some interesting findings: as I said above, we use ECDSA and here the snippet from the blogpost of @stribika:

> 2. ECDSA with SHA256, SHA384 or SHA512 depending on key size
> ...
>  Number 2 here involves NIST suckage and should be disabled as well. Another important disadvantage of DSA and ECDSA is that it uses randomness for each signature. If the random numbers are not the best quality, then it is possible to recover the secret key.

Maybe it would be also nice to ask @stribika for a review of our findings and changes.

@atomic111 what do you think? something I missed? Do you have time to do this in the next week, if not - its fine, I can do this and you can review it :)

**Comment by atomic111** [comment]
@artem-sidorenko no update of ciphers, macs and kexs needed. but we have to update the ssh host keys according to the list in https://github.com/dev-sec/ssh-baseline/pull/76

**Comment by artem-sidorenko** [comment]
@atomic111 Ok, I'll provide a PR in the next days

**Comment by artem-sidorenko** [comment]
thanks:)
