### ISSUE TITLE
The cookbooks fails on Amazon Linux.

### ISSUE THREAD

**Issue by jonasduarte** [dev-sec/chef-ssh-hardening#180]
Guys, 

Since ohai v13.0.0, the attribute "platform_family" for Amazon Linux retrieves "amazon", instead of "rhel", therefore the cookbook is failing.

To get it fixed, I add the value "amazon" to the code block below, on the default attribute file.

############################################################

# Define the service name for sshd
case node['platform_family']
when 'rhel', 'fedora', 'suse', 'freebsd', 'gentoo', 'amazon'
  default['jd_ssh_hardening']['sshserver']['service_name'] = 'sshd'
else
  default['jd_ssh_hardening']['sshserver']['service_name'] = 'ssh'
end

############################################################

Best regards,

**Comment by jonasduarte** [comment]
@chris-rock just did. I hope it helps.

Best,

**Comment by artem-sidorenko** [comment]
Resolved via #181
