### ISSUE TITLE
allowtcpforwarding with sftp enabled is declared twice

### ISSUE THREAD

**Issue by daften** [dev-sec/chef-ssh-hardening#182]
In the template https://github.com/dev-sec/chef-ssh-hardening/blob/master/templates/default/opensshd.conf.erb if you look for allowtcpforwarding, if you enable sftp, it would be declared twice with the hardcoded value overriding the one you set

**Comment by artem-sidorenko** [comment]
@daften thanks for raising this issue! You are right, `AllowTcpForwarding` is present in the sftp section by the end of file. From my understanding of sshd man page, the second option is part of the `Match` block. So it applies only to the sftp group, but not to the global section. Do I get something wrong here?

**Comment by daften** [comment]
You are very correct @artem-sidorenko . I missed that, highlighting for files in my IDE isn't as great as i thought it seems. Thanks for the feedback.
