### ISSUE TITLE
Cookbook not matching Controls

### ISSUE THREAD

**Issue by rreilly-edr** [dev-sec/chef-ssh-hardening#190]
Hi, was not sure if i needed to open this here or on the ssh-baseline repo but i guess I will start here.
I have applied this cookbook to a node with no extra attributes outside of 
`default['ssh-hardening']['ssh']['server']['client_alive_interval'] = 600`
but When I run the controls against the node I get a failure on ssh-03 and ssh-10
```
expected: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
     got: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
```

Not sure how to resolv this.
thanks !
rob

**Comment by artem-sidorenko** [comment]
@rreilly-edr thanks for raising this issue! May I ask you for some futher details, like used distribution and its version?

**Comment by rreilly-edr** [comment]
Yes of course! 
ubuntu 16.04 
chef-client 13.5.3

**Comment by artem-sidorenko** [comment]
@rreilly-edr I can not reproduce it:( Can you maybe tell me the cookbook version and baseline version/commit you are using?

**Comment by rreilly-edr** [comment]
```
commit 32611c30f4f7397162c7f286fb426cac6941b038
Merge: 9d7cbf2 bdb4030
Author: Christoph Hartmann <chris@lollyrock.com>
Date:   Thu Mar 15 15:27:07 2018 +0100

    Merge pull request #188 from dev-sec/chris-rock/amazonlinux
    
    amazonlinux support
```

``
Versions
2.3.1
```

**Comment by artem-sidorenko** [comment]
@rreilly-edr sorry for a late response, I was on a parental leave for several months.

I can't really reproduce it, do you still observe this issue?

```bash
$ cd ssh-baseline/
$ git checkout 2.3.1
$ cd ../chef-ssh-hardening/
$ git checkout v2.3.1
$ vi .kitchen.yml
$ git diff
diff --git a/.kitchen.yml b/.kitchen.yml
index 2154cd8..c0c1fdd 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -31,7 +31,8 @@ suites:
   - recipe[ssh-hardening]
   verifier:
     inspec_tests:
-      - https://github.com/dev-sec/ssh-baseline
+      - path: ../ssh-baseline
+            #      - https://github.com/dev-sec/ssh-baseline
 - name: rhel-with-disabled-pam
   includes:
     - centos-6.8
$ export CHEF_VERSION=13.5.3
$ kitchen verify ubuntu-16
....
Profile Summary: 68 successful controls, 0 control failures, 0 controls skipped
Test Summary: 100 successful, 0 failures, 0 skipped
```

**Comment by rreilly-edr** [comment]
I will take a look as soon as I can and report back. Thanks!

**Comment by artem-sidorenko** [comment]
@rreilly-edr I'm closing this issue as it wasn't possible to reproduce it. Feel free to reopen if needed
