### ISSUE TITLE
Errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by florian-asche** [dev-sec/chef-ssh-hardening#195]
Hello,

I am using the latest version on Ubuntu 18.04.
`cookbook 'ssh-hardening', '~> 2.3.1'`

```
Linux dexter 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@dexter:/etc/ssh# cat /etc/issue
Ubuntu 18.04 LTS \n \l
```

```
/etc/ssh/ssh_config line 71: Unsupported option "rhostsrsaauthentication"
/etc/ssh/ssh_config line 74: Unsupported option "rsaauthentication"

```

**Comment by artem-sidorenko** [comment]
@florian-asche thanks for this issue! Is this related to the #194 ?

**Comment by florian-asche** [comment]
yes, it is.

**Comment by frederikbosch** [comment]
See [the PR I created in the SSH baseline repo](https://github.com/dev-sec/ssh-baseline/pull/108). I am also looking for Ubuntu 18.04 support. Hopefully that will help to get some green lights.
