### ISSUE TITLE
Change log level for SFTP Subsystem

### ISSUE THREAD

**Issue by rediculum** [dev-sec/chef-ssh-hardening#199]
This attribute is missing in order to define another log level of the sftp subsystem (default is VERBOSE)

**Comment by chris-rock** [comment]
@rediculum would you like to add a PR to make it happen?

**Comment by rediculum** [comment]
Done
PR #200

**Comment by artem-sidorenko** [comment]
Resolved via #200

**Comment by rediculum** [comment]
Do you have an estimation when you release a new version including this?

**Comment by artem-sidorenko** [comment]
@rediculum 2.5.0 is released
