### ISSUE TITLE
Default value for ['ssh']['allow_tcp_forwarding'] breaks Chef Zero

### ISSUE THREAD

**Issue by pkuczynski** [dev-sec/chef-ssh-hardening#93]
The default value for `['ssh']['allow_tcp_forwarding'] = false` breaks Chef with error message:

`ERROR: Net::SSH::Exceptionremote forwarding request failed`

(I am using knife-zero but that should not make a difference here)

**Comment by artem-sidorenko** [comment]
@pkuczynski sorry for missing reaction. I'm closing this in order to cleanup the issues a bit. Feel free to reopen if the problem is still present
